crm/core/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import Home, Company, CreateCompany, CreateUser, Login, Main, Users
app_name = 'core'
urlpatterns = [
    path('', Main.as_view(), name='main'),
    path('company', Company.as_view(), name='company'),
    path('create-company/', CreateCompany.as_view(), name='create_company'),
    path('create-user/', CreateUser.as_view(), name='create_user'),
    path('login/', Login.as_view(), name='login'),
    
    path('users/', Users.as_view(), name='users'),
]

crm/crm/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls'))
]

crm/core/models.py
from django.db import models

# Create your models here.

crm/core/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
# Create your views here.
import time


class CustomHtmxMixin:
    def dispatch(self, request, *args, **kwargs):
        # import pdb; pdb.set_trace()
        self.template_htmx = self.template_name
        if not self.request.META.get('HTTP_HX_REQUEST'):
            self.template_name = 'components/include_block.html'
        else:
            time.sleep(1)
        return super().dispatch(request, *args, **kwargs)
    def get_context_data(self, **kwargs):
        kwargs['template_htmx'] = self.template_htmx
        return super().get_context_data(**kwargs)


class Home(TemplateView):
    template_name = 'home.html'


class Company(CustomHtmxMixin, TemplateView):
    template_name = 'company.html'
    def get_context_data(self, **kwargs):
        kwargs['title'] = 'Компания 1'
        return super().get_context_data(**kwargs)

class CreateCompany(CustomHtmxMixin, TemplateView):
    template_name = 'create_company.html'
    def get_context_data(self, **kwargs):
        kwargs['title'] = 'Создать компанию'
        return super().get_context_data(**kwargs)

class CreateUser(CustomHtmxMixin, TemplateView):
    template_name = 'create_user.html'
    def get_context_data(self, **kwargs):
        kwargs['title'] = 'Создать пользователя'
        return super().get_context_data(**kwargs)

class Login(TemplateView):
    template_name = 'login.html'

class Main(CustomHtmxMixin, TemplateView):
    template_name = 'main.html'
    def get_context_data(self, **kwargs):
        kwargs['title'] = 'Все компании'
        return super().get_context_data(**kwargs)

class Users(CustomHtmxMixin, TemplateView):
    template_name = 'users.html'
    def get_context_data(self, **kwargs):
        kwargs['title'] = 'Все пользователи'
        return super().get_context_data(**kwargs)

crm/core/templates/base.html
<!doctype html>
<html lang="en">
{% load static %}
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap CSS -->
    <link href="{% static 'assets/dist/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <script src="{% static 'js/htmx.min.js' %}"></script>
    
    <title>{{title}}</title>
</head>

<body>

    <header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
        <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="#">CRM</a>
        <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <input class="form-control form-control-dark w-100" type="text" placeholder="Поиск" aria-label="Search">
        <ul class="navbar-nav px-3">
            <li class="nav-item text-nowrap">
                <a class="nav-link" href="#">Вийти</a>
            </li>
        </ul>
    </header>
    <div class="container-fluid">
        <div class="row">
            {% include 'components/sidebarMenu.html' %}
            <progress id="content-loader" class="htmx-indicator" max="100"></progress>
            <div id="main-content">
            {% block content %}
            
            {% endblock %}
            </div>
        </div>
    </div>
    <script src="{% static 'assets/dist/js/bootstrap.bundle.min.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/feather-icons@4.28.0/dist/feather.min.js"></script>
    <script src="{% static 'js/dashboard.js' %}"></script>
    <script src="{% static 'js/script.js' %}"></script>
</body>
</html>

crm/core/templates/company.html
<main data-title = "{{title}}" class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
	<div class="row g-3 mt-3">
		<div class="col-md-12">
			<div class="card">
				<div class="card-body">

					<input type="hidden" value="agents" name="type" id="type">
					<div class="row">

						<div class="col-6">
							<p id="org_id" style="display:none">1293</p>
							<div class="org_header">Контактні дані</div>
							<p>
								<a href="" data-toggle="modal" data-target="#add_contact" id="new_contact">Добавить <span data-feather="plus-circle"></span> </a>
							</p>
							<div class="org_table">
								<table class="slide_1_to_m " id="contacts">
									<thead>
									</thead>
									<colgroup>
										<col width="7%">
										<col width="5%">
										<col width="5%">
										<col width="4%">
										<col width="1%">
									</colgroup>
									<tbody>
										<tr>
											<td><b>ПІБ</b></td>
											<td><b>Телефон(и)</b></td>
											<td><b>Email(ы)</b></td>
											<td><b>Посада</b></td>
											<td>&nbsp;</td>
										</tr>
										<tr id="">
											<td><span id="contact_name1261">Іванов Іван Іванович</span></td>
											<td><span id="contact_phones1261">3807777777 <br></span></td>
											<td><span id="contact_emails1261"><a href="mailto:as@as.as">as@as.as</a> <br></span></td>
											<td><span id="contact_dolzhnost1261">Керівник</span></td>
											<td>
												<a href="#">редактувати</a>
												<a href="#">видалити</a>
											</td>
										</tr>
									</tbody>
								</table>
							</div>
							<div>
								<div class="org_header mt-3">Документи компанії </div>
								<div class="clear"></div>
								<div style="min-height: 100px;min-height: 400px width: 100%; overflow:auto; border: solid 1px black;" class="mt-1">
									<p>Документи не завантажені</p>
									<table width="100%" class="org_table ">
										<colgroup>
											<col width="50%">
											<col width="30%">
											<col width="20%">
										</colgroup>
										<tbody>
											<tr id="1">
												<td><a href="#" target="_blank" title="">document.pdf</a></td>
												<td>02.02.2002</td>
												<td class="red">
													<a href="javascript:if(confirm('Подтвердите удаление')) delete())">X видалити</a>
												</td>
											</tr>
											<tr id="2">
												<td><a href="#" target="_blank" title="">document.pdf</a></td>
												<td>02.02.2002</td>
												<td class="red">
													<a href="javascript:if(confirm('Подтвердите удаление')) delete()">X видалити</a>
												</td>
											</tr>
										</tbody>
									</table>
								
									<div class="mt-3 me-2 mb-3">
										<button type="button" class="btn btn-sm btn-primary float-end">
											<span class="glyphicon glyphicon-cloud-upload"></span> Завантижити файли
										</button>
										<div class="clear"></div>
									</div>
								</div>
								
							</div>
							<div>
								<div class="org_header mt-3">Рахунок та договір для клієнта</div>
								<a href="#" style="font-weight:bold">Нова оплата</a>
								<a href="#">Усі платежі</a>
								<div class="clear"></div>
								<form action="" method="post" enctype="multipart/form-data" id="rekvizits_form" class="divtop5 form_create_platezh" novalidate="" autocomplete="off">
									<table width="100%" class="org_table">
										<tbody>
											<tr>
												<td style="width:50%">Постачальник </td>
												<td>
													<div class="col-12">
														<select class="form-select" id="" required>
															<option>ООО Приклад</option>
														</select>
													</div>
												</td>
											</tr>
											<tr>
												<td style="width:50%">Послуга</td>
												<td>
													<div class="col-12">
														<select class="form-select" id="" required>
															<option>Послуга</option>
														</select>
													</div>
												</td>
											</tr>
											<tr class="summ_block">
												<td style="width:50%">Сума</td>
												<td><input class="form-control" type="number" value="10000" step="100" required="" id=""> </td>
											</tr>
											<tr>
												<td class="org_td_header">Договір:</td>
												<td><input id="create_dog" name="create_dog" type="checkbox"></td>
											</tr>
											<tr>
												<td class="org_td_header">Реквізити </td>
												<td><a href="" onclick="showRevizits()">+</a></td>
											</tr>
											<tr>
												<td colspan="2">
													<script>
														function showRevizits() {
															event.preventDefault();
															var image = document.getElementById('rekvizits_block');
															image.style.display = (image.style.display == 'none') ? 'block' : 'none';
														}
													</script>
													<div class="mb-3" id="rekvizits_block" style="display:none">
														<table width="100%" align="left">
															<tbody>
																<tr>
																	<td>ІПН</td>
																	<td>
																		<input id="id_rekvizit-inn" maxlength="12" name="rekvizit-inn" type="text" value="1513070654">
																		<p>
																			<button style="padding: 2px; margin-top: 5px;font-size: 10px;" type="button" class="btn btn-info">Заполнить данные по ИНН</button>
																		</p>
																		<span id=""></span>
																	</td>
																</tr>
																<tr>
																	<td>КПП</td>
																	<td><input type="text" name="rekvizit-kpp" maxlength="12" id="id_rekvizit-kpp"> </td>
																</tr>
																<tr>
																	<td>Фірма</td>
																	<td><input type="text" name="rekvizit-name" maxlength="200" id="id_rekvizit-name"> </td>
																</tr>
																<tr>
																	<td>ОГРН</td>
																	<td><input type="text" name="rekvizit-ogrn" maxlength="200" id="id_rekvizit-ogrn"> </td>
																</tr>
																<tr>
																	<td>Посада в і.п.</td>
																	<td><input type="text" name="rekvizit-dolzhnost" maxlength="200" id="id_rekvizit-dolzhnost"> </td>
																</tr>
																<tr>
																	<td>Посада в р.п.</td>
																	<td><input type="text" name="rekvizit-dolzhnost_rod" maxlength="200" id="id_rekvizit-dolzhnost_rod"> </td>
																</tr>
																<tr>
																	<td>ПІБ в р.п.</td>
																	<td><input type="text" name="rekvizit-director_rod" maxlength="200" id="id_rekvizit-director_rod"> </td>
																</tr>
																<tr>
																	<td>ПІБ для підпису (в і.п.)</td>
																	<td><input type="text" name="rekvizit-director" maxlength="200" id="id_rekvizit-director"> </td>
																</tr>
																<tr>
																	<td></td>
																	<td> </td>
																</tr>
																<tr>
																	<td>На основі чого чинний</td>
																	<td><input type="text" name="rekvizit-osnovanie" maxlength="200" id="id_rekvizit-osnovanie"> </td>
																</tr>
																<tr>
																	<td>Юрид.адрес</td>
																	<td><input type="text" name="rekvizit-yur_address" maxlength="200" id="id_rekvizit-yur_address"> </td>
																</tr>
																<tr>
																	<td>Пошт.адрес</td>
																	<td><input type="text" name="rekvizit-pocht_address" maxlength="200" id="id_rekvizit-pocht_address"> </td>
																</tr>
																<tr>
																	<td>ОКПО</td>
																	<td><input type="text" name="rekvizit-okpo" maxlength="200" id="id_rekvizit-okpo"> </td>
																</tr>
																<tr>
																	<td>БИК</td>
																	<td><input type="text" name="rekvizit-bik_bank" maxlength="200" id="id_rekvizit-bik_bank">
																		<p><button style="padding: 2px; margin-top: 5px;font-size: 10px;" type="button" class="getdataforbik_rekvizits btn btn-info">Заполнить данные по БИК</button></p>
																		<span id="count_request_bic_api"></span>
																	</td>
																</tr>
																<tr>
																	<td>Назва банку</td>
																	<td><input type="text" name="rekvizit-name_bank" maxlength="200" id="id_rekvizit-name_bank"> </td>
																</tr>
																<tr>
																	<td>К/с</td>
																	<td><input type="text" name="rekvizit-ksc" maxlength="200" id="id_rekvizit-ksc"> </td>
																</tr>
																<tr>
																	<td>Розр. р.</td>
																	<td><input type="text" name="rekvizit-rsc" maxlength="200" id="id_rekvizit-rsc"> </td>
																</tr>
																<input type="hidden" value="93" name="platezh_org_id">
															</tbody>
														</table>
														<div class="text-right divtop5">
															<input class="me-3" type="button" value="Сохранить реквизиты">
														</div>
													</div>
												</td>
											</tr>
											<tr>
												<td class="org_td_header"></td>
												<td> </td>
											</tr>
										</tbody>
									</table>
									<button type="submit">Зберегти</button>
								</form>
							</div>
							<div>
								<br><br>
								<div class="org_header divtop5">Розмова з робітниками</div>
								<div class="clear"></div>
								<div style="height: 300px; width: 100%; overflow:auto; border: solid 1px black; font-size: 12px;">
								</div>
								<p class="mt-2"><input type="button" value="Отправить сообщение"></p>
								<div class="clear"></div>
								<br>
							</div>
							<div class="clear"></div>
						</div>
						<div class="col-6">
							<form action="" method="post" enctype="multipart/form-data">
								<table width="100%" class="org_table">
									<colgroup>
										<col width="30%">
										<col width="70%">
									</colgroup>
									<tbody>
										<tr>
											<td class="org_header" colspan="2">Детальная інформація про компанію</td>
										</tr>
										<tr>
											<th>Компанія:</th>
											<td>ООО Приклад</td>
										</tr>
										<tr>
											<th>Дата створення карти:</th>
											<td>02.02.2002</td>
										</tr>
										<tr>
											<th>ОКВЭД розділ</th>
											<td>E - щось робить<small></small></td>
										</tr>
										<tr>
											<th>ОКВЭД відділ</th>
											<td>38 - щось робить<small></small></td>
										</tr>
										<tr>
											<th>ОКВЭД</th>
											<td>38.1 - щось робить<small></small></td>
										</tr>

										<tr>
											<th>Країна:</th>
											<td>Україна</td>
										</tr>
										<tr>
											<th>Регіон:</th>
											<td>Київська область</td>
										</tr>
										<tr>
											<th>Місто:</th>
											<td>Київ

											</td>
										</tr>
										<tr>
											<th>Адрес:</th>
											<td>04044, --. --. --.</td>
										</tr>

										<tr>
											<th></th>
											<td> </td>
										</tr>
										<tr>
											<td class="org_td_header">ІПН:</td>
											<td>9014010202

											</td>
										</tr>
										<tr>
											<th>КПП:</th>
											<td>231400202</td>
										</tr>

									</tbody>
								</table>
								<table width="100%">
									<colgroup>
										<col width="30%">
										<col width="70%">

									</colgroup>
									<tbody>

										<tr>
											<td class="org_header" colspan="2">Дія</td>
										</tr>
										<tr>
											<th>Менеджер:</th>
											<td> <a href="#">Іванов Іван</a> </td>
										</tr>

										<tr>
											<th>Історія передачі карток:</th>
											<td>

											</td>
										</tr>

										<tr>
											<td class="org_td_header" colspan="2">Стан:

											</td>
										</tr>
										<tr id="1293">
											<td colspan="2">
												<div style="height: 300px; width: 100%; overflow:auto; border: solid 1px black; font-size: 12px;">
													<span id="">

														<b>02.02.2002 15:55 :</b> Зареєстровано 02.02.2002 15:55<br>
													</span>
												</div>

												<br>
												<p class="show_comment_block"><input type="button" value="Добавить комментарий"></p>

												<div class="comment_block" style="display:none">
													<div id="comment_form1293"><input type="hidden" name="csrfmiddlewaretoken" value="0hBlVbSLRPboEGdeg2J1MMGA8kGmBMb6YaSgPGOtp3ixs0xEbRAgt10djOLOGMyj">
														<textarea name="new_comment" id="new_comment1293" rows="5"></textarea>
														<input type="button" class="save_comment" value="Сохранить">
													</div>
												</div>

											</td>
										</tr>

										<tr>
											<th class="" colspan="2"></th>
										</tr>
										<tr>
											<td colspan="2"></td>
										</tr>
										<tr>
											<th class="">Статус</th>
											<td>
												<div><select name="" class="">
														<option class="" value=""></option>
														<option value="">---------</option>

														<option value="1" selected="">Низький</option>

														<option value="2">Середній</option>

														<option value="3">Високий</option>

														<option value="4">Куплено</option>

														<option value="5">Відмова</option>

													</select>
												</div>
											</td>
										</tr>
										<tr>
											<th>Наступний контакт:</th>
											<td>
												<div class="">
													<input type="text" value="02.02.2002 15:55:14">
												</div>
											</td>
										</tr>
									</tbody>
								</table>
								<input type="submit" class="btn btn-sm btn-primary mb-2" value="сохранить">
							</form>
						</div>
						<hr>
					</div>
				</div>
			</div>
		</div>
</main>

crm/core/templates/components/include_block.html
{% extends 'base.html' %}

{% block content %}
{% include template_htmx %}
{% endblock %}

crm/core/templates/components/sidebarMenu.html
<nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
    <div class="position-sticky pt-3">
        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
            <span>Компанії</span>
        </h6>
        <ul class="nav flex-column mb-2">
            <li class="nav-item ">
                {% url 'core:main' as core_main_page %}
                <a class="nav-link {% if request.path == core_main_page %}active{% endif %}" 
                href="{{core_main_page}}"
                hx-get="{{core_main_page}}"
                hx-target="#main-content"
                hx-push-url="true"
                hx-indicator = "#content-loader"
                hx-on="htmx:beforeRequest: event.detail.target.innerHTML = ''"
                hx-custom='title'
                >
                    <span data-feather="file-text"></span>
                    Усі Компанії
                </a>
            </li>
            <li class="nav-item">
                {% url 'core:create_company' as create_company_page %}
                <a class="nav-link {% if request.path == create_company_page %}active{% endif %}" 
                href="{{create_company_page}}"
                hx-get="{{create_company_page}}"
                hx-target="#main-content"
                hx-push-url="true"
                hx-indicator = "#content-loader"
                hx-on="htmx:beforeRequest: event.detail.target.innerHTML = ''"
                hx-custom='title'
                >
                    <span data-feather="file-text"></span>
                    Створити 
                    <span data-feather="plus-circle"></span>
                </a>
            </li>
        </ul>
        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
            <span>Менеджери</span>
        </h6>
        <ul class="nav flex-column mb-2">
            <li class="nav-item">
                {% url 'core:users' as users_page %}
                <a class="nav-link {% if request.path == users_page %}active{% endif %}" 
                href="{{users_page}}"
                hx-get="{{users_page}}"
                hx-target="#main-content"
                hx-push-url="true"
                hx-indicator = "#content-loader"
                hx-on="htmx:beforeRequest: event.detail.target.innerHTML = ''"
                hx-custom='title'
                >
                    <span data-feather="users"></span>
                    Усі Менеджери
                </a>
            </li>
            <li class="nav-item">
                {% url 'core:create_user' as create_user_page %}
                <a class="nav-link {% if request.path == create_user_page %}active{% endif %}" 
                href="{{create_user_page}}"
                hx-get="{{create_user_page}}"
                hx-target="#main-content"
                hx-push-url="true"
                hx-indicator = "#content-loader"
                hx-on="htmx:beforeRequest: event.detail.target.innerHTML = ''"
                hx-custom='title'
                >
                    <span data-feather="users"></span>
                    Додати
                    <span data-feather="plus-circle"></span>
                </a>
            </li>
        </ul>
        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
            <span>Аналітика</span>
        </h6>
        <ul class="nav flex-column mb-2">
            <li class="nav-item">
                <a class="nav-link" href="#">
                    <span data-feather="layers"></span>
                    Звіт 1
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">
                    <span data-feather="layers"></span>
                    Звіт 2
                </a>
            </li>
        </ul>
        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
            <span>Налаштування</span>
        </h6>
        <ul class="nav flex-column mb-2">
            <li class="nav-item">
                <a class="nav-link" href="#">
                    <span data-feather="layers"></span>
                    Налаштування 1
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">
                    <span data-feather="layers"></span>
                    Налаштування 2
                </a>
            </li>
        </ul>
    </div>
</nav>

crm/core/templates/create_company.html
      <main data-title = "{{title}}" class="col-md-9 ms-sm-auto col-lg-10 px-md-4">

        <h2 class="title m-5">Створити компанію</h2>
        <div class="row g-3">

          <div class="col-md-5 col-lg-6">

            <form class="needs-validation" novalidate>
              <div class="row g-3">




                <div class="col-12">
                  <label for="email" class="form-label">Email <span class="text-muted">(email)</span></label>
                  <input type="email" class="form-control" id="email" placeholder="you@example.com">
                  <div class="invalid-feedback">
                    Please enter a valid email address for shipping updates.
                  </div>
                </div>

                <div class="col-12">
                  <label for="address" class="form-label">Телефон</label>
                  <input type="text" class="form-control" id="address" placeholder="1234" required>
                  <div class="invalid-feedback">
                    Введіть текст ....
                  </div>
                </div>

                <div class="col-12">
                  <label for="address" class="form-label">Name</label>
                  <input type="text" class="form-control" id="address" placeholder="1234" required>
                  <div class="invalid-feedback">
                    Введіть текст ....
                  </div>
                </div>

                <div class="col-12">
                  <label for="address2" class="form-label">Text <span class="text-muted">(Textarea)</span></label>
                  <textarea class="form-control" name="name"></textarea>
                </div>

                <div class="col-12">
                  <label for="country" class="form-label">Країна</label>
                  <select class="form-select" id="country" required>
                    <option value="">Виберіть країну...</option>
                    <option>Україна</option>
                  </select>
                  <div class="invalid-feedback">
                    Please select a valid country.
                  </div>
                </div>

                <div class="col-12">
                  <label for="state" class="form-label">Регіон</label>
                  <select class="form-select" id="state" required>
                    <option value="">Выберіть регіон...</option>
                    <option>Львівська область</option>
                  </select>
                  <div class="invalid-feedback">
                    Please provide a valid state.
                  </div>
                </div>

                <div class="col-12">
                  <label for="state" class="form-label">Місто</label>
                  <select class="form-select" id="state" required>
                    <option value="">Выберіть місто...</option>
                    <option>Львів</option>
                  </select>
                  <div class="invalid-feedback">
                    Please provide a valid state.
                  </div>
                </div>

                <div class="col-12">
                  <label for="email" class="form-label">Email <span class="text-muted">(email)</span></label>
                  <input type="email" class="form-control" id="email" placeholder="you@example.com">
                  <div class="invalid-feedback">
                    Please enter a valid email address for shipping updates.
                  </div>
                </div>

                <div class="col-12">
                  <label for="address" class="form-label">Телефон</label>
                  <input type="text" class="form-control" id="address" placeholder="1234" required>
                  <div class="invalid-feedback">
                    Введіть текст ....
                  </div>
                </div>

              </div>



              <hr class="my-4">




              <div class="col-6">
                <button class="w-100 btn btn-primary btn-lg" type="submit">Створити</button>
              </div>

            </form>
          </div>
        </div>
      </main>

crm/core/templates/login.html
<!doctype html>
<html lang="en">
{% load static %}
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Bootstrap CSS -->
  <link href="{% static 'assets/dist/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/style.css' %}" rel="stylesheet">
  <title>Авторизація</title>
</head>

<body>
  <main class="form-signin">
    <form>

      <h1 class="h3 mb-3 fw-normal">Авторизація</h1>
      <label for="inputEmail" class="visually-hidden">Email</label>
      <input type="email" id="inputEmail" class="form-control" placeholder="Email address" required autofocus>
      <label for="inputPassword" class="visually-hidden">Пароль</label>
      <input type="password" id="inputPassword" class="form-control mt-2" placeholder="Password" required>

      <button class="w-100 btn btn-lg btn-primary" type="submit">Вхід</button>

    </form>
  </main>




  <script src="{% static 'assets/dist/js/bootstrap.bundle.min.js' %}"></script>

</body>

</html>

crm/core/templates/main.html
    <main data-title = "{{title}}" class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
      

      

      <h2 class="title m-5">Усі компанії</h2>
      <div class="table-responsive">
        <table class="table table-bordered">
            <col width="5%" /> 
    		<col width="6%" /> 
    		<col width="7%" /> 
    		<col width="5%" /> 
    		<col width="20%" /> 
    		<col width="5%" /> 
          <thead>
            <tr>
              <th>Дата контакту</th>
              <th>Організація</th>
              <th>Країна, регіон</th>
              <th>Місто</th>
              <th>Стан</th>
              <th>Статус</th>
            </tr>
          </thead>
          <tbody>
               <tr>
                <td>02.02.2002</td>
                <td><a 
                href="{% url 'core:company' %}"
                hx-get="{% url 'core:company' %}"
                hx-target="#main-content"
                hx-push-url="true"
                hx-indicator = "#content-loader"
                hx-on="htmx:beforeRequest: event.detail.target.innerHTML = ''"
                >ООО Приклад</a><br> ІПН (1234567890)</td>
                <td>Україна, Область</td>
                <td>Місто</td>
                <td>
                      02.02.2002 15:55 : Зареєстровано 02.02.2002 15:55<br>
                      02.02.2002 15:55 : Текст коментарія<br>
                      02.02.2002 15:55 : Текст коментарія 2<br>
                      
                </td>
                <td>Перший контакт</td>
              </tr>
              <tr>
                <td>02.02.2002</td>
                <td><a href="#">ООО Приклад</a><br> ІПН (1234567890)</td>
                <td>Країна, Область</td>
                <td>Місто</td>
                <td>
                      02.02.2002 15:55 : Зареєстровано 02.02.2002 15:55<br>
                      02.02.2002 15:55 : Текст коментарія<br>
                      02.02.2002 15:55 : Текст коментарія 2<br>
                      
                </td>
                <td>Перший контакт</td>
              </tr>
              <tr>
                <td>02.02.2002</td>
                <td><a href="#">ООО Приклад</a><br> ІПН (1234567890)</td>
                <td>Україна, Область</td>
                <td>Місто</td>
                <td>
                      02.02.2002 15:55 : Зареєстровано 02.02.2002 15:55<br>
                      02.02.2002 15:55 : Текст коментарія<br>
                      02.02.2002 15:55 : Текст коментарія 2<br>
                      
                </td>
                <td>Перший контакт</td>
              </tr>
          </tbody>
        </table>
      </div>
    </main>